### ISSUE TITLE
Publish the helm chart to a registry

### ISSUE THREAD

**Issue by day1118** [opencost/opencost-helm-chart#10]
It would be much easier to install and track if the chart is published to a registry with a tag

**Comment by toscott** [comment]
Any thoughts on using:
https://github.com/helm/chart-releaser-action

**Comment by toscott** [comment]
I'm gonna try to take a stab at this.

**Comment by AjayTripathy** [comment]
Hey @toscott I'm supportive of this if you want to merge the fork back in!
