### ISSUE TITLE
Custom pricing configmap

### ISSUE THREAD

**Issue by HoussemCharf** [opencost/opencost-helm-chart#108]
# Description
OpenCost supports custom pricing for on-premise environments [here](https://www.opencost.io/docs/configuration/on-prem#custom-pricing-using-the-opencost-helm-chart). You can introduce this pricing by deploying a configmap in the environment sadly this isn't integrated into the helm chart and is deployed separately. If you go about it the way it is now it's not explicitly clear in the values as you have to introduce them as extraEnv and ExtraMount
```opencost:
  exporter:
    extraEnv:
      # The default config path is read only, for customizing we have to swap spots.
      CONFIG_PATH: "/tmp/custom-config"
    extraVolumeMounts:
      - mountPath: /tmp/custom-config
        name: custom-configs
extraVolumes:
  - name: custom-configs
    configMap:
      name: opencost-conf
```

# Expected Behavior
As an improvement, we should include the configmap for users to be defined in their values as they see fit with the possibility to use their own configmap if they want to.

**Comment by insider89** [comment]
@HoussemCharf Am I understand correctly, that with this implementation we cannot provide `AWS intergration`(as it's require that in configmap we have aws.json instead if default.json, what currently hardcoded), and allow only `On-Premises Pricing` integration?

**Comment by HoussemCharf** [comment]
@insider89, this PR was to help improve the on-premise mode by providing a way to provide that in the helm values.yaml. 
as far as AWS pricing, it is fetched automatically from 
`https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/{node_region}/index.json`

**Comment by insider89** [comment]
@HoussemCharf I mean AWS SPOT instance prices. We need to provide additional configuration for it, as described [here](https://www.opencost.io/docs/configuration/AWS). So it's not possible to provide AWS SPOT configuration with this change. Thx for confirming it.
