### ISSUE TITLE
GCP Permission issues

### ISSUE THREAD

**Issue by Lukiido** [opencost/opencost-helm-chart#111]
Hey all!

I am trying to setup opencost to monitor a test gcp cluster for finical improvement etc. I have given an API key Compute Admin and Billing Project Manager. When doing this I get an error about not being able to view reserved instances. Should I be giving different permissions on this? or should I just follow the cost analyzer doc for the permissions the key or SA would need?

Thanks!

**Comment by mattray** [comment]
Is this a duplicate of https://github.com/opencost/opencost-helm-chart/issues/87?

**Comment by Lukiido** [comment]
No, in this case I am getting told that I cannot view reserved instances with error 403 compute.commitments.list permissions for my project. I have tested with a key that has compute admin, and a key that had all APIs.

When I use a SA and it's key, opencost won't start at all, that SA has project manager for billing, computer viewer and user.

So what I am wondering is there a doc with proper permission sets a key or SA needs.

**Comment by mattray** [comment]
Kubecost has a doc with more comprehensive settings: https://docs.kubecost.com/install-and-configure/install/cloud-integration/gcp-out-of-cluster

OpenCost doesn't have billing reconciliation but I would recommend reviewing that for anything that may have been overlooked in the OpenCost docs: https://www.opencost.io/docs/configuration/gcp-opencost

If you find the answer and it's something lacking in our documentation, please let us know. Thanks!

**Comment by svartalf** [comment]
It took me some time to deal with it, but I managed to run OpenCost in the GCP Managed Kubernetes.

The following instructions are for the OpenCost v1.20.0 (the latest version of this helm chart at the moment of writing this comment).

1. Create an API key and restrict its usage only to Billing API (no need to add Compute Engine API or BigQuery API to it) 
2. Create an IAM Service Account and add the following roles to it:
    - `roles/bigquery.user`
    - `roles/compute.viewer`
    - `roles/bigquery.dataViewer`
    - `roles/bigquery.jobUser`
    - `roles/iam.serviceAccountTokenCreator`

    For example, with this CLI command:
    ```bash
    $ gcloud projects add-iam-policy-binding dexter-general --member=serviceAccount:your-iam-service-account-email@your-project.iam.gserviceaccount.com --role=roles/bigquery.user
    ```

 3. Make sure you have the [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) enabled and configured properly
 4. Add the `roles/iam.workloadIdentityUser` role to link the IAM Service Account to the GCP one; simplest option would be to use the `gcloud` CLI tool again:
    ```bash
    $ gcloud iam service-accounts add-iam-policy-binding your-iam-service-account-email@your-project.iam.gserviceaccount.com --role roles/iam.workloadIdentityUser --member "serviceAccount:your-project.svc.id.goog[your-namespace/your-k8s-service-account-name]"
    ```
 5. Add the Workload Identity annotation to the K8S Service Account created by this chart
     ```yaml
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: your-iam-service-account-email@your-project.iam.gserviceaccount.com
    ```

6. Wait a few minutes for changes to propagate and restart the OpenCost pod(s) to pick up the changes
