### ISSUE TITLE
Incorrect behaviour after define prometheus bearer token values

### ISSUE THREAD

**Issue by debMan** [opencost/opencost-helm-chart#126]
When using the following values to define bearer token secret name and key, to connect to the prometheus, the helm template rendered to incorrect output:
- `.Values.opencost.prometheus.bearer_token_key`
- `.Values.opencost.prometheus.secret_name`

**Reproduce:**

Changes to values:
``` diff
     prometheus:
+      secret_name: spcld-opencost-prometheus-token
+      bearer_token_key: token
```

Changes in argoCD:

<img width="475" alt="image" src="https://github.com/opencost/opencost-helm-chart/assets/12995147/e92b1afa-4415-45dc-b332-dd408a2b9def">

**Comment by mattray** [comment]
I believe this has been fixed after reading through the code. @debMan if you get a chance to verify please reopen if this isn't the case.
