### ISSUE TITLE
Not able to fix s3 bucket in helm chart

### ISSUE THREAD

**Issue by ghaith-ajimi** [opencost/opencost-helm-chart#129]
Hi all, 
After setting up AWS Spot instance data feed configuration, I am not able to to add the s3 bucket configuration.
Am I missing something? 
Skipping AWS spot data download: operation error S3: ListObjects, https response error StatusCode: 400, error InvalidBucketName: The specified bucket is not valid.

**Comment by dwbrown2** [comment]
@ghaith-ajimi can you share how you are deploying Opencost and the configuration you're using?
