### ISSUE TITLE
Missing opencost.cloudIntegrationSecret value in the opencost chart README.md and values.yaml

### ISSUE THREAD

**Issue by sossickd** [opencost/opencost-helm-chart#146]
I will looking into how to add the VolumeMount for cloud-integration and found that there is a opencost.cloudIntegrationSecret value not documented in the [README.md](https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/README.md)
or the [values.yaml](https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml)

Only found this value by looking in templates/deployment.yaml

**Comment by mattray** [comment]
The PR was opened, needs a review: https://github.com/opencost/opencost-helm-chart/pull/145
