### ISSUE TITLE
Image tag is always set to latest (if unset)

### ISSUE THREAD

**Issue by duncan485** [opencost/opencost-helm-chart#153]
Because the default value for `tag:` is set to the `latest` , the template will use that if tag is unset, instead of the appversion in Chart.yaml. I discovered this when upgrading from 1.22.2 to 1.26.2. Is this intentional ?

**Comment by mattray** [comment]
The [manifest in the opencost/opencost](https://github.com/opencost/opencost/blob/develop/kubernetes/opencost.yaml#L145) repo is set to latest, but I think it makes sense for the Helm chart to match the Chart.yaml. PRs definitely welcome
