### ISSUE TITLE
Missing opencost.ui.enabled value in README of opencost chart

### ISSUE THREAD

**Issue by kohbis** [opencost/opencost-helm-chart#158]
`opencost.ui.enabled` exists in [values.yaml](https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L286) but not in [README.md](https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/README.md?plain=1#L123)

It seems to be getting deleted automatically for some reason.
https://github.com/opencost/opencost-helm-chart/pull/156/files

**Comment by mattray** [comment]
I'm pretty sure it's right here: https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/templates/deployment.yaml#L198

That value determines whether or not to enable the UI container and it seems to be working fine in my local testing. If you set it to `false` in your own `values.yaml` it won't render the UI container deployment.

**Comment by mattray** [comment]
Nevermind, just re-read your comment and I'm adding it to the README with https://github.com/opencost/opencost-helm-chart/pull/159
