### ISSUE TITLE
Container `opencost` keeps exiting with error code 2 when trying to hit RateCard API

### ISSUE THREAD

**Issue by akivalam-hbk** [opencost/opencost-helm-chart#160]
### Setup 

1. We have an AKS private cluster running on which opencost is deployed using the helm-chart [here](https://github.com/opencost/opencost-helm-chart)
2. The secrets service-key.json, cloud-integration.json along with the service principal and associated custom roles were created as specified [here](https://www.opencost.io/docs/configuration/azure)

### Issue 
1. Upon trying to access the "Cloud Costs", seeing a "502 Bad Gateway" error in the UI 
2. The opencost container keeps restarting with `exit code 2` and seems to not proceed further after the log 
`2023-12-21T09:52:38.134643073Z INF Using ratecard query OfferDurableId eq 'MS-AZR-0003p' and Currency eq 'USD' and Locale eq 'en-US' and RegionInfo eq 'US'`

**Comment by mattray** [comment]
Is this still an issue? Were you using 1.108?
