### ISSUE TITLE
[Feature request] namespaceOverride possibility 

### ISSUE THREAD

**Issue by vovkanaz** [opencost/opencost-helm-chart#161]
Hi, we have found some gaps in Opencost chart, unfortunately  Opencost chart doesn't support any possibility for changing the target namespace e.g. https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L11. It would be nice to have such option, thanks in advance.

**Comment by mattray** [comment]
I'm on vacation, but I'll take a look at this early next year unless someone else provides a PR.

**Comment by toscott** [comment]
@vovkanaz - The namespace can be changed by installing the helm release directly in the target namespace. Are you saying you have a use case where the helm release needs to be in one namespace, but the deployed artifacts in a separate one?

**Comment by vovkanaz** [comment]
@toscott - We've created a custom helm chart, and Opencost has been used as a dependency, hence we can manage it only via Values. Unfortunately, HELM doesn't support any ability to manage [helm dependencies with different namespaces](https://stackoverflow.com/questions/68559495/helm-dependencies-with-different-namespaces). So, it would be nice to have the possibility to set a target namespace for Opencost as a dependency, even via values. ArgoCD Application in our case.

**Comment by mattray** [comment]
@vovkanaz we had support and removed it, but you've made a good case for supporting it again. If someone provides a PR I'd approve it as long as it continues to work with `helm --namespace`
