### ISSUE TITLE
Chart without envFrom to pass opencost-service-principal to export_csv_file

### ISSUE THREAD

**Issue by andreyolv** [opencost/opencost-helm-chart#168]
There is no possible to configure this using helm chart:
https://www.opencost.io/docs/integrations/csv-export

No envFrom in the deployment opencost template and values.yaml

**Comment by mattray** [comment]
I believe you'll want to set `opencost.exporter.env`

https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L170C1-L171C1

**Comment by andreyolv** [comment]
It worked out! Thanks!
