### ISSUE TITLE
Documentation and Installation Consistency Across docs and README and quick install steps

### ISSUE THREAD

**Issue by brito-rafa** [opencost/opencost-helm-chart#176]
A couple people pinged me individually about difficulty in installing prometheus example + opencost with helm + opencost via kubectl. They started using helm and then it did not work and then installing opencost with kubectl command.

We benefit the consistency across:
- https://github.com/opencost/opencost/blob/develop/kubernetes/opencost.yaml
- https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml

And supporting documentation:
- https://www.opencost.io/docs/installation/helm
- https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/README.md

The point is standardization of the prometheus namespace and helm RELEASE_NAME: 
A. opencost helm `values.yaml` expects prometheus running on namespace `prometheus-system`. The opencost helm README instructs to use RELEASE_NAME `prometheus`.
B. However, opencost docs suggests prometheus running on `prometheus` namespace with helm RELEASE_NAME `my-prometheus`.  The kubectl quick install uses these as a default values.
C. AFAIK, prometheus themselves do not suggest a default namespace for their installation.

I suggest changing opencost helm chart for:
- the `values.yaml` to expect `prometheus` namespace with helm RELEASE_NAME `my-prometheus`. So it will be consistent with kubectl install + opencost docs.
- change the README to follow the same "managing with helm" doc page:
```
helm repo add opencost-charts https://opencost.github.io/opencost-helm-chart
helm repo update
```
And to install with command
```
helm install opencost opencost-charts/opencost --namespace opencost --create-namespace -f values.yaml
```

**Comment by mattray** [comment]
I'm definitely supportive about syncing these across the board, I'll approve any PRs or I can get around to it later this week. We should probably emphasize the Helm chart over the manifest given most folks will probably end up needing some sort of customization.

**Comment by brito-rafa** [comment]
This change required three PRs across the board:
opencost-helm-chart (minor tweak): https://github.com/opencost/opencost-website/pull/199
opencost: https://github.com/opencost/opencost/pull/2519
opencost-website: https://github.com/opencost/opencost-website/pull/199

**Comment by mattray** [comment]
All merged. Thanks @brito-rafa!
