### ISSUE TITLE
opencost on k8s ubuntu server with disabled ipv6

### ISSUE THREAD

**Issue by ehaagh** [opencost/opencost-helm-chart#184]
Hi

I install opencost on my k8s cluster, k8s is installed on Ubuntu 22.04 server with disabled ipv6.

I get follow error:

Get "https://[::1]:6443/api/v1/namespaces/opencost/resourcequotas": dial tcp [::1]:6443: connect: cannot assign requested address

I have install it on a test cluster with ipv6, then it work fine. But I cant get ipv6 on production cluster.

Do you have a sulution?

Best regards 
Erling Haagh

**Comment by mattray** [comment]
Is that this issue?
https://www.opencost.io/docs/troubleshooting#address-family-not-supported-by-protocol-error-message

We may need to come up with a standardized fix for that.

**Comment by ehaagh** [comment]
Yes, but I can't see how to correct in confog and remove line 62
