### ISSUE TITLE
Create official Artifact Hub organization

### ISSUE THREAD

**Issue by mkilchhofer** [opencost/opencost-helm-chart#188]
A long time ago, I created an Artifact Hub repo linking to this repo here to increase visibility of this great CNCF project.
> ![grafik](https://github.com/opencost/opencost-helm-chart/assets/7290987/47d83e4c-744d-4b25-8e04-f33615ff4b94)

I think you should create an organization on Artifact Hub and then I will teardown the listing in my personal space.
Listing a CNCF project on Artifact Hub is part of the CLOMonitor checks:
> ![grafik](https://github.com/opencost/opencost-helm-chart/assets/7290987/a63dfba8-83a1-4325-883c-0b588b7e9973)
> 
> Source: https://clomonitor.io/projects/cncf/opencost

/cc: @asdfgugus as you already mentioned this one time offline to me.

**Comment by mkilchhofer** [comment]
Okay it seems that @asdfgugus talked to @mattray during KubeCon in Paris.
He already created the org and I transfered over the repo from my personal space to the org:
> ![grafik](https://github.com/opencost/opencost-helm-chart/assets/7290987/ae3717d1-151e-4feb-99ac-56748e01ee80)

I think it is the best to assign this issue directly to @asdfgugus

**Comment by asdfgugus** [comment]
Yes this is correct. As soon as @mattray sends me his username for Artifacthub via Slack, I will transfer the organization to him. 
A big thanks to @mkilchhofer for your help!

**Comment by mattray** [comment]
I've accepted the invitation to ArtifactHub and my username is `mattray`
