### ISSUE TITLE
Support default deny with external Prometheus

### ISSUE THREAD

**Issue by asdfgugus** [opencost/opencost-helm-chart#189]
Currently there is no support for a default deny setup, if using an external Prometheus. 

This can be achieved by adding the ability to set extraIngress and extraEgress. 
There is already a PR open [#183](https://github.com/opencost/opencost-helm-chart/pull/183) to support extraEgress, but only if using an internal Prometheus.

**Comment by mattray** [comment]
As long as it's not a breaking change I don't think there would be any objections to a PR for it.
