### ISSUE TITLE
Publish the helm index to make the chart discoverable

### ISSUE THREAD

**Issue by toscott** [opencost/opencost-helm-chart#19]
What we need to do:
1. Create a new branch in the repository named "gh-pages"
2. Bump the chart version or delete the current release/tag (will likely fail otherwise since the run was incomplete)
3. Re run the publish workflow
4. Verify Settings/Pages > Source branch is set to gh-pages

Why we need it
Creating the new branch will allow the chart-releaser-action github action to create and pubilsh an index.yaml file with the chart information. 
View here for more details: https://github.com/helm/chart-releaser-action

Rerunning the publish workflow will create an index.yaml in the gh-pages branch.

Setting the source branch to gh pages will expose that branch as a website: https://opencost.github.io/opencost-helm-chart/
View here for more details: https://pages.github.com/

**Comment by toscott** [comment]
@shalom-cyera  - These steps must be done by a maintainer of this repsoitory.

**Comment by AjayTripathy** [comment]
This something you can handle @mattray ?

**Comment by mattray** [comment]
Done.

**Comment by thomsonnapitupulu** [comment]
Where can we see the location of index.yaml? I still got error "index not found" when try to add the repo via Terraform.
<img width="947" alt="Screen Shot 2023-02-23 at 16 37 49" src="https://user-images.githubusercontent.com/7758567/221082489-3aacccbd-0528-4e83-8182-424fe75a5bb9.png">

**Comment by dwbrown2** [comment]
@thomsonnapitupulu this should now be resolved, but please let us know if you're still having issues
