### ISSUE TITLE
Add network policies support

### ISSUE THREAD

**Issue by asdfgugus** [opencost/opencost-helm-chart#21]
Network policies are required to run OpenCost in a default deny environment. This is quite common in a production environment.
Ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/

If you would like to implement this feature, I would offer you my contribution. 
Let me know!

**Comment by mattray** [comment]
@asdfgugus If you'd like to contribute a PR, we'd welcome this feature. Off the top of my head we need to ensure OpenCost has access to Prometheus in whatever namespace it would be in.

**Comment by asdfgugus** [comment]
Currently Prometheus has to be installed manually. Will this change in the near future? (Helm subchart)

**Comment by mattray** [comment]
I don't think that's planned, but we need to ensure that if they're using the internal Prometheus service it's accessible. I'm happy to test it once you have it, since I do that for one of my installs.
https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L59

**Comment by asdfgugus** [comment]
I will test it on several different Kubernetes distributions. Currently I am

**Comment by asdfgugus** [comment]
Sorry, accidentally closed the issue. 
---
Currently I am to busy. I will try get it done by the end of the week.

**Comment by asdfgugus** [comment]
I added some networkpolicies to my fork. There are still some policies needed but before I continue I would like to get some feedback whether this corresponds to your expectations. Please check the diffs here: https://github.com/opencost/opencost-helm-chart/compare/main...asdfgugus:opencost-helm-chart:main 
Thanks in advance!

**Comment by mattray** [comment]
If you want to make a PR and mark it as "Draft" or "WIP" we can start reviewing it and giving feedback.
