### ISSUE TITLE
Helm Chart image versioned with opencost released image

### ISSUE THREAD

**Issue by nicolodallavalentinaclearscore** [opencost/opencost-helm-chart#23]
We should change the helm chart release to match the Opencost release.
At the moment in the values.yaml there is set "tag: latest". 
Unfortunately in this way, the helm chart cannot be versioned by controlling what app version image has been released within

Example of the requested change 
chart 1.0.3 has been set to 1.9.8 with the latest image 
    
    image:
      registry: quay.io
      repository: kubecost1/kubecost-cost-model
      tag: latest

to example:
chart 1.0.4 has been set to 1.100.0

    image:
      registry: quay.io
      repository: kubecost1/kubecost-cost-model
      tag: prod-1.100.2

**Comment by toscott** [comment]
>  the helm chart cannot be versioned by controlling what app version image has been released within

At the moment, new opencost releases do not require chart releases. The image tag can be overwritten at install time to get to something more static, or left at latest to obtain updates on each deploy. 

Is there an underlying reason that you are recommending the default tag in the helm chart should specify an image that isn't obvious? Are you concerned about backwards compatibility issues or something?

**Comment by nicolodallavalentinaclearscore** [comment]
Thanks for the reply. Usually, on the other community projects when there is a new code release with new features or security bug fixes there is a new release to match those changes.
In this way, we can control what's contained in each Helm chart release especially when there will be bigger releases with breaking changes, major upgrades or migrations.
Also for security reasons and stability, I don't want to download the "latest" each time but leave the users the ability to upgrade when need it without using kustomize.

**Comment by mkilchhofer** [comment]
This should definitively be implemented as it is best practice for all helm charts.
I wasn't aware of this discussion here when I implemented exaclty this in my PR over there: #27
