### ISSUE TITLE
Allocation API response return incorrect duration minutes

### ISSUE THREAD

**Issue by seeeun-cho** [opencost/opencost-helm-chart#232]
Our clusters encountered an incorrect duration issue after applying [PR](https://github.com/opencost/opencost-helm-chart/pull/179/files#diff-064c32b24e65e735590b9ad29d1faedf21bf89fa79f56544cf4ababb60f6a0f6R94-R96) the OpenCost to [ghcr.io/opencost/opencost:v1.109](http://ghcr.io/opencost/opencost:v1.109) (and other versions in this registry).
Symptom is that the [allocation API](https://www.opencost.io/docs/integrations/api#allocation) response (/allocation?window=15m&aggregate=pod) returns a 10-minute duration, even when the pod has been running for over 15 minutes.
I used to use [quay.io/kubecost1/kubecost-cost-model:prod-1.105.2](http://quay.io/kubecost1/kubecost-cost-model:prod-1.105.2) which was no issue on this.

Is there a way to get the same response as the previous result?

**Comment by ameijer** [comment]
As per our discussion in https://cloud-native.slack.com/archives/C03D56FPD4G/p1730239559121949 , recommend reducing ETL_RESOLUTION_SECONDS to 60 to catch short lived pods
