### ISSUE TITLE
Typo in image.tag in chart version 1.42.1

### ISSUE THREAD

**Issue by verdel** [opencost/opencost-helm-chart#233]
The `@` symbol is missing before `sha256` in `opencost.image.tag` and `opencost.ui.image.tag` in chart version `1.42.1`. The sha256 hashes of the images are also incorrect.

**Comment by AjayTripathy** [comment]
Thanks @verdel ! Want to make a PR?

**Comment by verdel** [comment]
> Thanks @verdel ! Want to make a PR?

Yes, no problem. Already done.
