### ISSUE TITLE
Configure duration of data to store

### ISSUE THREAD

**Issue by mattray** [opencost/opencost-helm-chart#26]
OpenCost currently defaults to 15 days of data retention, we should probably make this configurable and expose it at the Helm chart level.

**Comment by mattray** [comment]
This is configured by Prometheus ```'--storage.tsdb.retention.time=15d'```

**Comment by AjayTripathy** [comment]
Note that the primary blocker here is prometheus scale. Making this arbitrarily large isn't possible without increasing size of prometheus/backing disk/etc.

**Comment by boniek83** [comment]
Isn't this an issue of documentation? If it depends on prometheus and opencost depends on provided instance, then opencost itself cannot do anything about it.

**Comment by mattray** [comment]
Closing because this is a Prometheus configuration issue.
