### ISSUE TITLE
Expose PROMETHEUS_SERVER_ENDPOINT as a configurable value

### ISSUE THREAD

**Issue by Pokom** [opencost/opencost-helm-chart#3]
There are scenarios where an operator may want to use a `prometheus` instance that does not run alongside `opencost`. We should provide the ability to define the `PROMETHEUS_SERVER_ENDPOINT` when deploying the helm chart.

**Comment by mattray** [comment]
No objections, looking forward to the PR.

**Comment by AjayTripathy** [comment]
SGTM!

**Comment by Pokom** [comment]
Looks like @ts-mini beat me to the punch and was able resolve this in #7 :muscle:
