### ISSUE TITLE
Add CI check to ensure PR's bump versions

### ISSUE THREAD

**Issue by Pokom** [opencost/opencost-helm-chart#30]
Currently it is possible to merge changes into `main` that do not bump the `appVersion` in the `Charts.yaml` file. There should be some safeguards in place to prevent this to ensure `main` can always be published.

**Comment by mkilchhofer** [comment]
@mattray @sntxrr you can assign that to me 🙋‍♂️

**Comment by mkilchhofer** [comment]
@Pokom Thx for assigning it to me 👍 PR is ready. Shared the CI workflow of [argo-helm](https://github.com/argoproj/argo-helm) where I invest my main contributor/maintainer time :-)

**Comment by Pokom** [comment]
Awesome thank you @mkilchhofer!!! I can take a look when I have a moment
