### ISSUE TITLE
OpenShift support for opencost-ui

### ISSUE THREAD

**Issue by debMan** [opencost/opencost-helm-chart#64]
Due to some security limitations on openshift, I've faced the following problems for `opencost-ui`:
- permission denied on `/var/www` dir for nginx when starting pod. Need to change ownership and filemod
- port 80 is not available to open. It's related to default nginx configurations

These configurations should be editable with helm values

**Comment by mattray** [comment]
If someone wants to open a PR for this and test it with I'm sure it would be appreciated.

**Comment by mattray** [comment]
I believe this is going to be addressed by https://github.com/opencost/opencost/pull/2130

**Comment by mattray** [comment]
OpenCost no longer runs the UI as root on port 80, so this shouldn't be an issue anymore.
