### ISSUE TITLE
opencost ui must run as root user ?

### ISSUE THREAD

**Issue by mo-saeed** [opencost/opencost-helm-chart#77]
Hello, 

I am trying to install opencost-ui as non-root user and i get this error 
```
sed: can't create temp file '/var/www/index.60cea723.jsXXXXXX': Permission denied
```
is there anyway to install the ui without the root user access?

**Comment by mattray** [comment]
Waiting on https://github.com/opencost/opencost/pull/1947 to go into the release.

**Comment by mattray** [comment]
It's in the upcoming 1.105 branch, so it'll be in the next release: https://github.com/opencost/opencost/commits/v1.105
