### ISSUE TITLE
Conflict with multiple declarations of volumeMounts in deployment.yaml

### ISSUE THREAD

**Issue by Caroline132** [opencost/opencost-helm-chart#85]
**Description**

There are multiple declarations of the `volumeMounts` field in the  [deployment.yaml](https://github.com/opencost/opencost-helm-chart/blob/1ecd5dd9443793a7d9cd1fcca92ce9015b6fc067/charts/opencost/templates/deployment.yaml#L1-L201) template.

Currently, the volumeMounts field can be specified in three ways in the values.yaml file:
1. By providing extraVolumeMounts values in `.Values.opencost.exporter.extraVolumeMounts`
2. By enabling the persistence in `.Values.opencost.exporter.persistence.enabled`
3. By providing extraVolumeMounts values in `.Values.opencost.ui.extraVolumeMounts`

So, this is preventing mounting of secrets for the service principal to the Azure API.

**Expected behavior**

Be able to enable all volumeMounts.

**Comment by dnskr** [comment]
The PR https://github.com/opencost/opencost-helm-chart/pull/81 fixes the issue.

**Comment by toscott** [comment]
This should be fixed with the latest helm chart: 1.16.0.
