### ISSUE TITLE
Issue with deploy by helm

### ISSUE THREAD

**Issue by ashestopalko** [opencost/opencost-helm-chart#87]
was provided by deploy gcp api key and prometheus url but see some another project number

ERR Failed to lookup reserved instance data: googleapi: Error 403: Compute Engine API has not been used in project 42275347607 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=42275347607 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.Help",
    "links": [
      {
        "description": "Google developers console API activation",
        "url": "https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=42275347607"
      }
    ]
  },
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadatas": {
      "consumer": "projects/42275347607",
      "service": "compute.googleapis.com"
    },
    "reason": "SERVICE_DISABLED"
  }
]
, accessNotConfigured

**Comment by ashestopalko** [comment]
app.kubernetes.io/version: 1.104.0
    helm.sh/chart: opencost-1.15.0
    also checked that for api key provided access to billing and cloud engine apis, and added gke nat ip to whitelist
    
    about env:
    tried to deploy to gke cluster for checking billing data of gke-cluster
    on cluster exist pormetheus with node exporters

**Comment by petewall** [comment]
I assume this is a GKE cluster?
The error message seems to indicate that there's some API that needs to be enabled for this project. Have you gone through the instructions on that URL?

**Comment by ashestopalko** [comment]
yes, trying to deploy opencost to GKE cluster,
but link don`t open by permission,-by project number in link - checked that`s not our project
but in project with GKE - needful APIs enabled, and provided to then access for api-key which use in deploy-process

**Comment by vovabuh** [comment]
Hi
I have the same issue when try to deploy opencost by helm
`WRN Failed to load auth secret, or was not mounted: Secret does not exist
 ERR Failed to lookup reserved instance data: googleapi: Error 403: Compute Engine API has not been used in project 42275347607 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=42275347607 then retry.`
it seems that the opencost don’t see current project
how the opencost realise what is it a project current?
maybe we make a mistake with ApiKey?

**Comment by BulatSaif** [comment]
Hello, I faced the same error, even project "42275347607" in error is same

**Comment by BulatSaif** [comment]
I found an issue. API keys have permission denied. Removing the `methods = ["GET*"]` fixed the problem. 
 I still see the `Compute Engine API has not been used in project 42275347607 before or it is disabled` error, but the application starts and the pod is healthy.

**Comment by Lukiido** [comment]
Hey,

I am having a similar issue but for me the projectID is todo, I am unable to override the gcp.json config it seems. I have an api created but it doesn't seem to contain the project ID itself. Am I missing a step?

**Comment by mattray** [comment]
I believe this will fix it: https://github.com/opencost/opencost/pull/2122

**Comment by mattray** [comment]
This was fixed in https://github.com/opencost/opencost-helm-chart/commit/005359db1a37ba699498a1a9d647e8fc3ccbda91
