### ISSUE TITLE
suggestion: adding init container for azure billing enrollment 

### ISSUE THREAD

**Issue by csimplestring** [opencost/opencost-helm-chart#91]
based on this link: https://www.opencost.io/docs/azure-prices#grant-billing-access-to-your-service-principal
a bash script is provided. 

Would it be good to run the bash script in an init container?

**Comment by mattray** [comment]
Updated link is here: https://www.opencost.io/docs/configuration/azure-prices#grant-billing-access-to-your-service-principal

I'll defer to others on executing a bash script from Helm, it feels wonky to me since you'd probably want to do it yourself once but I'm willing to hear counterarguments.
